
model_list = [
    "togetherai/CODELLAMA/CODELLAMA-13B-INSTRUCT-HF",
    "togetherai/CODELLAMA/CODELLAMA-34B-INSTRUCT-HF",
    "togetherai/CODELLAMA/CODELLAMA-7B-INSTRUCT-HF",
    "togetherai/META-LLAMA/LLAMA-2-70B-CHAT-HF",
    "togetherai/META-LLAMA/LLAMA-3-70B-CHAT-HF",
    "togetherai/META-LLAMA/LLAMA-3-8B-CHAT-HF",
    "togetherai/MISTRALAI/MISTRAL-7B-INSTRUCT-V0.2",
    "togetherai/MISTRALAI/MIXTRAL-8X22B-INSTRUCT-V0.1",
    "togetherai/MISTRALAI/MIXTRAL-8X7B-INSTRUCT-V0.1",
    "togetherai/MICROSOFT/WIZARDLM-2-8X22B",
    "togetherai/DEEPSEEK-AI/DEEPSEEK-CODER-33B-INSTRUCT",
    "togetherai/DEEPSEEK-AI/DEEPSEEK-LLM-67B-CHAT",
    "togetherai/NOUSRESEARCH/NOUS-CAPYBARA-7B-V1P9",
    "togetherai/NOUSRESEARCH/NOUS-HERMES-2-MISTRAL-7B-DPO",
    "togetherai/NOUSRESEARCH/NOUS-HERMES-2-MIXTRAL-8X7B-SFT",
    "togetherai/NOUSRESEARCH/NOUS-HERMES-2-YI-34B",
    "togetherai/COGNITIVECOMPUTATIONS/DOLPHIN-2.5-MIXTRAL-8X7B",
    "togetherai/QWEN/QWEN1.5-32B-CHAT",
    "togetherai/QWEN/QWEN1.5-72B-CHAT",
    "togetherai/ZERO-ONE-AI/YI-34B-CHAT"
]
