name: JSON Model Test

on:
  workflow_dispatch:
    inputs:
      model_name:
        description: 'Model Name'
        required: true
        default: '*'
        
jobs:
  test-model:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openai
        
    - name: Run Model Test
      env:
        API_KEY: ${{ secrets.API_KEY }}
        API_BASE: ${{ secrets.API_BASE }}
      run: python evaluate.py --api_key $API_KEY --base_url $API_BASE --model_engine ${{ github.event.inputs.model_name }}